export const EXPERIMENT_ACTIONS = {
  EXPERIMENTS_LOAD_REQUEST: 'EXPERIMENTS_LOAD_REQUEST',
  EXPERIMENTS_LOAD_SUCCES: 'EXPERIMENTS_LOAD_SUCCES',
  EXPERIMENTS_LOAD_FAIL: 'EXPERIMENTS_LOAD_FAIL',
  EXPERIMENT_VARIANT_REQUEST: 'EXPERIMENT_VARIANT_REQUEST',
  EXPERIMENT_VARIANT_SUCCES: 'EXPERIMENT_VARIANT_SUCCES',
  EXPERIMENT_VARIANT_FAIL: 'EXPERIMENT_VARIANT_FAIL',
  EXPERIMENT_RUN: 'EXPERIMENT_RUN',
};

export const getVariantAction = (experimentLabel, experimentKey) => ({
  type: EXPERIMENT_ACTIONS.EXPERIMENT_VARIANT_REQUEST,
  experimentLabel,
  experimentKey,
});
