export const EXPERIMENT_ACTIONS = {
  EXPERIMENTS_LOAD_REQUEST: 'EXPERIMENTS_LOAD_REQUEST',
  EXPERIMENTS_LOAD_SUCCES: 'EXPERIMENTS_LOAD_SUCCES',
  EXPERIMENTS_LOAD_FAIL: 'EXPERIMENTS_LOAD_FAIL',
  EXPERIMENT_RUN: 'EXPERIMENT_RUN',
};
