export const EXPERIMENT_ACTIONS = {
  EXPERIMENT_LOAD: 'EXPERIMENT_LOAD',
  EXPERIMENT_RUN: 'EXPERIMENT_RUN',
  EXPERIMENT_SUCCES: 'EXPERIMENT_SUCCESS',
  EXPERIMENT_FAIL: 'EXPERIMENT_FAIL',
};

export const loadExperiments = () => {
  return {
    type: EXPERIMENT_ACTIONS.EXPERIMENT_LOAD,
  };
};
